### ISSUE TITLE
Drawing Around Objects Demo is crashing

### ISSUE THREAD

**Issue by goldensunliu** [adamschwartz/letters#5]
the last example demo on http://adamschwartz.co/letters/ is hanging and making the page blank when click on element which triggers the test for drawing around objects. Is it just me?

**Comment by adamschwartz** [comment]
I added that last example as a way to show what Letters is capable of on faster machines. Everyone’s individual mileage may vary. It makes 50,000 draw attempts, so can definitely hang on some machines. But it runs in under 5 seconds on my MBP.

I’d absolutely love it if folks helped me out with further optimizations to the library, but note that what Letters does to avoid collisions (checking every pixel in a drawn region) is inherently slow. My recommendation to the community is to use Letters to create images in advance (not at runtime) unless you rendering a low number of glyphs (`~<500`) in a a small font size (`~<20`).

The [huge dense example image](https://github.com/adamschwartz/letters/blob/gh-pages/images/letters-huge-dense.png) took several minutes to render on my machine. To prevent Chrome from hanging, I ran ~20,000 draw iterations at a time, waited for them to complete, and then drew more. I also set the canvas opacity to 0, although I’m not sure if that helped. All told I ran about a million draw iterations to complete it.

I hope this helps!

**Comment by goldensunliu** [comment]
hmm strange, my MBP isn't really happy with it. With a fresh restart and plenty of CPU, the page was still crashing. On the contribution note, I am happy to take a look on our current collision avoidance detection when I get some time.
